### ISSUE TITLE
TypeError: Unknown encoding: iso-8859-1

### ISSUE THREAD

**Issue by buckett** [myadzel/saz2har#9]
When trying to convert a saz file I get:

```
TypeError: Unknown encoding: iso-8859-1
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at HarBuilder._parseQuery (/home/buckett/node_modules/saz2har/lib/har-builder.js:268:52)
    at Array.forEach (<anonymous>)
    at HarBuilder._parseQueries (/home/buckett/node_modules/saz2har/lib/har-builder.js:101:13)
    at HarBuilder.build (/home/buckett/node_modules/saz2har/lib/har-builder.js:95:10)
    at SazParser.sazParser.on (/home/buckett/node_modules/saz2har/lib/converter.js:87:20)
    at emitOne (events.js:116:13)
    at SazParser.emit (events.js:211:7)
    at SazParser._done (/home/buckett/node_modules/saz2har/lib/saz-parser.js:85:10)
```

**Comment by myadzel** [comment]
Can you attach file?

**Comment by buckett** [comment]
Sorry, the file contains cookies and secure headers, however looking inside the archive I've found the file with the problem (I think), it's path is `raw/14_s.txt`:

[14_s.txt](https://github.com/myadzel/saz2har/files/3803973/14_s.txt)

**Comment by myadzel** [comment]
OK. What version of Node.js do you use?

**Comment by buckett** [comment]
$ node --version
v12.4.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88

**Comment by myadzel** [comment]
Fixed in master.

**Comment by myadzel** [comment]
Have you checked your performance? Can I close this problem?

**Comment by laksprasad** [comment]
@myadzel Sorry, I may be missing something here but the same issue seems to be happening if the charset appears in all CAPs. (Content-Type header charset directive is case insensitive and though lowercase is preferred, some sites still use uppercase :( ). Could we change the check to be case insensitive or convert `responseCharset` to lowercase before invoking this call?
Attached sample failure case - 
[sample_s.txt](https://github.com/myadzel/saz2har/files/10983862/sample_s.txt)
